### ISSUE TITLE
Table of content .Rmd file

### ISSUE THREAD

**Issue by sirine-chahma** [UBC-MDS/DSCI_522_group_401#22]
I tried to show the table of content in the final report using ` toc: true` but is doesn't seem to work as the document that I create is a github_document. Do you have any idea why?

**Comment by singh-karanpal** [comment]
I am happy that we have discussed this issue in person. As we know now that our report does have LaTex code in it so our output has to be rendered as ` github_document: pandoc_args: --webtex`. Due to this reason, we won't be rendering our report in HTML but `toc` can only be included in HTML report. So, we had to made a choice and dropped `toc` idea.

I am going ahead and closing this issue for now.
